#!/usr/bin/env python

import sys
import datetime
from os import path

log_dir = '/Users/cai/Dropbox/Writing/'


def main():

    # Details for timestamp
    now = datetime.datetime.now()
    date = now.strftime('%Y-%m-%d')
    time = now.strftime('%H:%M')

    # Use stdin if it's full. This enables pipes etc.
    # Cheers to https://stackoverflow.com/a/11111088/2883198 for how to accept pipes in python.
    input_stream: str
    if not sys.stdin.isatty():
        input_stream = sys.stdin

    # Otherwise, prompt for text
    else:
        print("Enter text of entry. Linebreaks acceptable. Double linebreak to commit.")
        # Get multi-line input from prompt
        # Thanks to https://stackoverflow.com/a/11664675/2883198
        sentinel = ''  # Will terminate when this is seen (i.e. double-enter is pressed).
        input_stream = '\n'.join(iter(input, sentinel))

    # Build entry text

    # Entry starts with doc separator and time
    entry: str = (f"===\n"
                  f"{time}:\n")
    # Then add message and separate with new line
    for line in input_stream:
        entry += line
    entry += '\n'

    # Write entry to file
    with open(path.join(log_dir, f"{date}.txt"), mode="a", encoding="utf-8") as log_file:
        log_file.write(entry)


if __name__ == '__main__':

    main()
